[package]
name = "flutterinstaller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.25"
dirs = "4.0.0"
spinners = "2.0.0"